import pg from 'pg';
import jwt from 'jsonwebtoken';
const { Pool } = pg;
const DATABASE_URL = process.env.DATABASE_URL || '';
const JWT_SECRET = process.env.JWT_SECRET || '';
const pool = DATABASE_URL ? new Pool({ connectionString: DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false, max: 3, min: 0, idleTimeoutMillis: 30_000, connectionTimeoutMillis: 5_000, statement_timeout: 10_000, query_timeout: 12_000, keepAlive: true }) : null;
const DEFAULTS = { enabled:true,pushEnabled:true,reactionsEnabled:true,commentsEnabled:true,friendRequestsEnabled:true,messagesEnabled:true,storiesEnabled:true,remindersEnabled:true,groupEnabled:true,marketplaceEnabled:true,walletEnabled:true,quietMode:false };
function auth(req,res,next){const header=req.get('authorization')||'';const token=header.startsWith('Bearer ')?header.slice(7).trim():'';if(!token||!JWT_SECRET)return res.status(401).json({error:'authentication required'});try{req.user=jwt.verify(token,JWT_SECRET);return next();}catch{return res.status(401).json({error:'invalid or expired token'});}}
let schemaPromise;
async function ensureSchema(){if(!pool)throw new Error('database not configured');if(!schemaPromise)schemaPromise=pool.query(`CREATE TABLE IF NOT EXISTS notification_preferences(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, enabled BOOLEAN NOT NULL DEFAULT TRUE, push_enabled BOOLEAN NOT NULL DEFAULT TRUE, reactions_enabled BOOLEAN NOT NULL DEFAULT TRUE, comments_enabled BOOLEAN NOT NULL DEFAULT TRUE, friend_requests_enabled BOOLEAN NOT NULL DEFAULT TRUE, messages_enabled BOOLEAN NOT NULL DEFAULT TRUE, stories_enabled BOOLEAN NOT NULL DEFAULT TRUE, reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE, group_enabled BOOLEAN NOT NULL DEFAULT TRUE, marketplace_enabled BOOLEAN NOT NULL DEFAULT TRUE, wallet_enabled BOOLEAN NOT NULL DEFAULT TRUE, quiet_mode BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS fynx_notifications(id TEXT NOT NULL, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, target_id TEXT, source_username TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), read_at TIMESTAMPTZ, PRIMARY KEY(id,user_id)); CREATE INDEX IF NOT EXISTS fynx_notifications_user_idx ON fynx_notifications(user_id,created_at DESC);`).catch(e=>{schemaPromise=undefined;throw e;});return schemaPromise;}
const columns={enabled:'enabled',pushEnabled:'push_enabled',reactionsEnabled:'reactions_enabled',commentsEnabled:'comments_enabled',friendRequestsEnabled:'friend_requests_enabled',messagesEnabled:'messages_enabled',storiesEnabled:'stories_enabled',remindersEnabled:'reminders_enabled',groupEnabled:'group_enabled',marketplaceEnabled:'marketplace_enabled',walletEnabled:'wallet_enabled',quietMode:'quiet_mode'};
function clean(row){return Object.fromEntries(Object.entries(columns).map(([key,column])=>[key,row?.[column]==null?DEFAULTS[key]:Boolean(row[column])]));}
async function read(userId){const result=await pool.query(`INSERT INTO notification_preferences(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING RETURNING *`,[userId]);return result.rows[0] || (await pool.query('SELECT * FROM notification_preferences WHERE user_id=$1',[userId])).rows[0];}
export function registerNotificationPreferenceRoutes({app}){app.get('/api/notification-preferences',auth,async(req,res)=>{try{await ensureSchema();res.set('Cache-Control','no-store');return res.json({preferences:clean(await read(req.user.sub))});}catch(error){console.error('notification preferences get',error);return res.status(500).json({error:'notification preferences unavailable'});}});app.patch('/api/notification-preferences',auth,async(req,res)=>{try{await ensureSchema();const input=req.body?.preferences&&typeof req.body.preferences==='object'?req.body.preferences:req.body;const updates={};for(const [key,column] of Object.entries(columns)){if(input?.[key]!==undefined){if(typeof input[key]!=='boolean')return res.status(400).json({error:`invalid notification preference: ${key}`});updates[column]=input[key];}}if(!Object.keys(updates).length)return res.status(400).json({error:'at least one notification preference is required'});const keys=Object.keys(updates);const params=[req.user.sub,...keys.map(k=>updates[k])];const cols=['user_id',...keys].join(',');const vals=['$1',...keys.map((_,i)=>`$${i+2}`)].join(',');const assignments=keys.map((k,i)=>`${k}=$${i+2}`).join(',');const result=await pool.query(`INSERT INTO notification_preferences(${cols}) VALUES(${vals}) ON CONFLICT(user_id) DO UPDATE SET ${assignments},updated_at=NOW() RETURNING *`,params);res.set('Cache-Control','no-store');return res.json({preferences:clean(result.rows[0])});}catch(error){console.error('notification preferences update',error);return res.status(500).json({error:'notification preferences update failed'});}});
app.get('/api/notifications',auth,async(req,res)=>{try{await ensureSchema();const userId=req.user.sub;const safety=(await pool.query(`SELECT account_status,status_note,updated_at FROM fynx_account_safety WHERE user_id=$1`,[userId])).rows[0];if(safety&&safety.account_status&&safety.account_status!=='ACTIVE'){const id=`safety-status-${userId}-${safety.updated_at?new Date(safety.updated_at).getTime():0}`;const title=safety.account_status==='LOCKED'?'FYNX Safety — Account locked':'FYNX Safety — Account restricted';const message=safety.status_note||'Your account has been restricted because your activity did not follow the FYNX Community Guidelines. Review the details and use the appeal process if you believe this was a mistake.';await pool.query(`INSERT INTO fynx_notifications(id,user_id,type,title,message,created_at) VALUES($1,$2,'SAFETY',$3,$4,$5) ON CONFLICT(id,user_id) DO UPDATE SET title=EXCLUDED.title,message=EXCLUDED.message`,[id,userId,title,message,safety.updated_at||new Date()]);}const result=await pool.query(`SELECT id,type,title,message,EXTRACT(EPOCH FROM created_at)*1000 AS timestamp,target_id,source_username,read_at FROM fynx_notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[userId]);res.set('Cache-Control','no-store');return res.json({notifications:result.rows.map(row=>({id:row.id,type:row.type,title:row.title,message:row.message,timestamp:Number(row.timestamp),targetId:row.target_id,sourceUsername:row.source_username,read:Boolean(row.read_at)}))});}catch(error){console.error('notifications get',error);return res.status(500).json({error:'notifications unavailable'});}});
app.post('/api/notifications/:id/read',auth,async(req,res)=>{try{await ensureSchema();const id=String(req.params?.id||'').trim();if(!id||id.length>200)return res.status(400).json({error:'invalid notification'});await pool.query(`UPDATE fynx_notifications SET read_at=COALESCE(read_at,NOW()) WHERE id=$1 AND user_id=$2`,[id,req.user.sub]);return res.json({ok:true});}catch(error){console.error('notification read',error);return res.status(500).json({error:'notification update failed'});}});
}
