import pg from 'pg';
import jwt from 'jsonwebtoken';
const { Pool } = pg;
const DATABASE_URL = process.env.DATABASE_URL || '';
const JWT_SECRET = process.env.JWT_SECRET || '';
const pool = DATABASE_URL ? new Pool({ connectionString: DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false, max: 3, min: 0, idleTimeoutMillis: 30_000, connectionTimeoutMillis: 5_000, statement_timeout: 10_000, query_timeout: 12_000, keepAlive: true }) : null;
const DEFAULTS = { enabled: true, messages: true, friends: true, groups: true, marketplace: true, reminders: true, sound: true, vibration: true };
function auth(req,res,next){const header=req.get('authorization')||'';const token=header.startsWith('Bearer ')?header.slice(7).trim():'';if(!token||!JWT_SECRET)return res.status(401).json({error:'authentication required'});try{req.user=jwt.verify(token,JWT_SECRET);return next();}catch{return res.status(401).json({error:'invalid or expired token'});}}
let schemaPromise;
async function ensureSchema(){if(!pool)throw new Error('database not configured');if(!schemaPromise)schemaPromise=pool.query(`CREATE TABLE IF NOT EXISTS notification_preferences(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, enabled BOOLEAN NOT NULL DEFAULT TRUE, messages BOOLEAN NOT NULL DEFAULT TRUE, friends BOOLEAN NOT NULL DEFAULT TRUE, groups BOOLEAN NOT NULL DEFAULT TRUE, marketplace BOOLEAN NOT NULL DEFAULT TRUE, reminders BOOLEAN NOT NULL DEFAULT TRUE, sound BOOLEAN NOT NULL DEFAULT TRUE, vibration BOOLEAN NOT NULL DEFAULT TRUE, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`).catch(e=>{schemaPromise=undefined;throw e;});return schemaPromise;}
function clean(row){return Object.fromEntries(Object.keys(DEFAULTS).map(k=>[k,row?.[k] == null ? DEFAULTS[k] : Boolean(row[k])]));}
export function registerNotificationPreferenceRoutes({app}){app.get('/api/notification-preferences',auth,async(req,res)=>{try{await ensureSchema();const result=await pool.query(`INSERT INTO notification_preferences(user_id) VALUES($1) ON CONFLICT(user_id) DO NOTHING RETURNING enabled,messages,friends,groups,marketplace,reminders,sound,vibration`,[req.user.sub]);let row=result.rows[0];if(!row)row=(await pool.query(`SELECT enabled,messages,friends,groups,marketplace,reminders,sound,vibration FROM notification_preferences WHERE user_id=$1`,[req.user.sub])).rows[0];res.set('Cache-Control','no-store');return res.json({preferences:clean(row)});}catch(error){console.error('notification preferences get',error);return res.status(500).json({error:'notification preferences unavailable'});}});app.patch('/api/notification-preferences',auth,async(req,res)=>{try{await ensureSchema();const input=req.body?.preferences&&typeof req.body.preferences==='object'?req.body.preferences:req.body;const updates={};for(const key of Object.keys(DEFAULTS)){if(input?.[key]!==undefined){if(typeof input[key]!=='boolean')return res.status(400).json({error:`invalid notification preference: ${key}`});updates[key]=input[key];}}if(!Object.keys(updates).length)return res.status(400).json({error:'at least one notification preference is required'});const keys=Object.keys(updates);const params=[req.user.sub,...keys.map(k=>updates[k])];const cols=['user_id',...keys].join(',');const vals=['$1',...keys.map((_,i)=>`$${i+2}`)].join(',');const assignments=keys.map((k,i)=>`${k}=$${i+2}`).join(',');const result=await pool.query(`INSERT INTO notification_preferences(${cols}) VALUES(${vals}) ON CONFLICT(user_id) DO UPDATE SET ${assignments},updated_at=NOW() RETURNING enabled,messages,friends,groups,marketplace,reminders,sound,vibration`,params);res.set('Cache-Control','no-store');return res.json({preferences:clean(result.rows[0])});}catch(error){console.error('notification preferences update',error);return res.status(500).json({error:'notification preferences update failed'});}});}
