import http from "node:http";
import { installFailureRecovery, createIdempotencyStore } from "./reliability.js";
import { createBackgroundJobQueue } from "./backgroundJobs.js";
import { registerMarketplaceSettlementRoutes } from "./marketplaceSettlement.js";
import { registerMarketplaceProtectionRoutes } from "./marketplaceProtection.js";
import { installSecurityHardening } from "./securityHardening.js";
import { registerRealtimeAssistantRoutes } from "./aiRealtimeRoutes.js";
import { registerPrivacyRoutes } from "./privacyRoutes.js";
import { registerProfileRoutes } from "./profileRoutes.js";
import { registerGroupRoutes } from "./groupRoutes.js";
import { registerNotificationPreferenceRoutes } from "./notificationPreferences.js";
import { registerAdminRoutes } from "./adminRoutes.js";
import { installPresencePrivacyGuard } from "./presencePrivacy.js";
import { installMediaPrivacyGuard } from "./mediaPrivacy.js";
import { installSocialHardening } from "./socialHardening.js";
import { installPrivateCachePolicy } from "./privateCachePolicy.js";
import { installMarketplaceMediaPrivacyGuard } from "./marketplaceMediaPrivacy.js";
import { installRequestResourceGuard } from "./requestResourceGuard.js";
import { installApiAbuseGuard } from "./apiAbuseGuard.js";

installPresencePrivacyGuard();
const originalCreateServer = http.createServer;
http.createServer = function fynxCreateServer(...args) {
  const server = originalCreateServer.apply(this, args);
  const app = args[0];
  if (app && typeof app.use === "function") {
    setImmediate(() => {
      installSecurityHardening({ app });
      installRequestResourceGuard(app);
      installApiAbuseGuard(app);
      registerMarketplaceSettlementRoutes({ app });
      registerMarketplaceProtectionRoutes({ app });
      registerRealtimeAssistantRoutes({ app });
      registerPrivacyRoutes({ app });
      registerProfileRoutes({ app });
      registerGroupRoutes({ app });
      registerNotificationPreferenceRoutes({ app });
      registerAdminRoutes({ app });
      installMediaPrivacyGuard(app);
      installSocialHardening(app);
      installPrivateCachePolicy(app);
      installMarketplaceMediaPrivacyGuard(app);
    });
  }
  server.keepAliveTimeout=65_000;
  server.headersTimeout=70_000;
  server.requestTimeout=30_000;
  server.maxRequestsPerSocket=1_000;
  server.maxConnections=500;
  let requests=0; let completed=0; let totalLatencyMs=0; let errors=0;
  server.on("request",(_req,res)=>{const startedAt=process.hrtime.bigint();requests+=1;res.on("finish",()=>{completed+=1;totalLatencyMs+=Number(process.hrtime.bigint()-startedAt)/1_000_000;if(res.statusCode>=500)errors+=1;});});
  const report=setInterval(()=>{if(!completed)return;const averageLatencyMs=totalLatencyMs/completed;console.log(`[fynx-metrics] requests=${requests} completed=${completed} errors5xx=${errors} avgLatencyMs=${averageLatencyMs.toFixed(1)}`);},60_000);report.unref();
  server.on("error",error=>{console.error("[fynx-http] server error",error);});
  const recovery=installFailureRecovery({server,pool:globalThis.__fynxPool||null,logger:console});
  globalThis.__fynxRecovery=recovery;
  globalThis.__fynxIdempotency=createIdempotencyStore({maxEntries:10_000,ttlMs:24*60*60*1000});
  globalThis.__fynxJobHandlers=globalThis.__fynxJobHandlers||{};
  const jobs=createBackgroundJobQueue({logger:console});
  globalThis.__fynxBackgroundJobs=jobs;
  void jobs.start().catch(error=>console.error("[fynx-jobs] startup failed",error?.message||error));
  return server;
};
