#!/usr/bin/env bash
set -euo pipefail
python3 - <<'PY'
from pathlib import Path
p=Path('backend/socialRoutes.js')
s=p.read_text()
if '/api/social/feed' not in s:
    add="""
  // FYNX Social Core — real posts, likes, comments, follows and protected post media.
  let socialSchemaPromise;
  const ensureSocialSchema = async () => {
    if (!socialSchemaPromise) socialSchemaPromise = pool.query(`
      CREATE TABLE IF NOT EXISTS social_posts (id BIGSERIAL PRIMARY KEY, author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, text TEXT NOT NULL DEFAULT '', visibility TEXT NOT NULL DEFAULT 'PUBLIC' CHECK (visibility IN ('PUBLIC','FRIENDS_ONLY')), media_id BIGINT REFERENCES message_media(id) ON DELETE SET NULL, media_type TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS social_posts_created_idx ON social_posts(created_at DESC);
      CREATE TABLE IF NOT EXISTS social_post_likes (post_id BIGINT NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(post_id,user_id));
      CREATE TABLE IF NOT EXISTS social_post_comments (id BIGSERIAL PRIMARY KEY, post_id BIGINT NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE, author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, text TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS social_post_comments_post_idx ON social_post_comments(post_id,created_at ASC);
      CREATE TABLE IF NOT EXISTS social_follows (follower_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, followed_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(follower_id,followed_id), CHECK(follower_id<>followed_id));
      CREATE INDEX IF NOT EXISTS social_follows_followed_idx ON social_follows(followed_id,created_at DESC);
    `).catch(e=>{socialSchemaPromise=undefined;throw e});
    return socialSchemaPromise;
  };
  const visibleSocialPost = async (id,userId) => { const r=await pool.query(`SELECT 1 FROM social_posts p WHERE p.id=$1 AND (p.author_id=$2 OR p.visibility='PUBLIC' OR (p.visibility='FRIENDS_ONLY' AND EXISTS(SELECT 1 FROM friendships f WHERE ((f.user_id=p.author_id AND f.friend_id=$2) OR (f.user_id=$2 AND f.friend_id=p.author_id)) AND f.status='accepted'))) AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=$2 AND b.blocked_id=p.author_id) OR (b.blocker_id=p.author_id AND b.blocked_id=$2))`,[id,userId]); return Boolean(r.rowCount); };
  app.get('/api/social/feed',auth,async(req,res)=>{try{await ensureSocialSchema();const limit=Math.min(Math.max(Number(req.query?.limit)||50,1),100);const r=await pool.query(`SELECT p.id,p.author_id,u.username author_username,u.display_name author_display_name,p.text,p.visibility,p.media_id,p.media_type,EXTRACT(EPOCH FROM p.created_at)*1000 timestamp,(SELECT COUNT(*) FROM social_post_likes l WHERE l.post_id=p.id) like_count,(SELECT COUNT(*) FROM social_post_comments c WHERE c.post_id=p.id) comment_count,EXISTS(SELECT 1 FROM social_post_likes l WHERE l.post_id=p.id AND l.user_id=$1) liked_by_current_user,EXISTS(SELECT 1 FROM social_follows f WHERE f.follower_id=$1 AND f.followed_id=p.author_id) followed_by_current_user FROM social_posts p JOIN users u ON u.id=p.author_id WHERE (p.author_id=$1 OR p.visibility='PUBLIC' OR (p.visibility='FRIENDS_ONLY' AND EXISTS(SELECT 1 FROM friendships f WHERE ((f.user_id=p.author_id AND f.friend_id=$1) OR (f.user_id=$1 AND f.friend_id=p.author_id)) AND f.status='accepted'))) AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=p.author_id) OR (b.blocker_id=p.author_id AND b.blocked_id=$1)) ORDER BY p.created_at DESC LIMIT $2`,[req.user.sub,limit]);res.json({posts:r.rows.map(x=>({id:String(x.id),authorId:String(x.author_id),authorUsername:x.author_username,authorDisplayName:x.author_display_name,text:x.text,visibility:x.visibility,mediaId:x.media_id==null?null:String(x.media_id),mediaType:x.media_type||null,mediaUrl:x.media_id==null?null:`/api/social/media/${x.media_id}`,timestamp:Number(x.timestamp),likeCount:Number(x.like_count),commentCount:Number(x.comment_count),likedByCurrentUser:Boolean(x.liked_by_current_user),followedByCurrentUser:Boolean(x.followed_by_current_user)}))})}catch(e){console.error('social feed',e);res.status(500).json({error:'social feed failed'})}});
  app.post('/api/social/posts',auth,async(req,res)=>{try{await ensureSocialSchema();const text=typeof req.body?.text==='string'?req.body.text.trim().slice(0,4000):'';const visibility=req.body?.visibility==='FRIENDS_ONLY'?'FRIENDS_ONLY':'PUBLIC';const mediaId=req.body?.mediaId==null?null:Number(req.body.mediaId);const mediaType=typeof req.body?.mediaType==='string'?req.body.mediaType.trim().toLowerCase():null;if(!text&&mediaId==null)return res.status(400).json({error:'post content is required'});if(mediaId!=null){if(!Number.isInteger(mediaId)||mediaId<1||!['image','video'].includes(mediaType))return res.status(400).json({error:'invalid post media'});const m=await pool.query('SELECT id FROM message_media WHERE id=$1 AND owner_id=$2',[mediaId,req.user.sub]);if(!m.rows[0])return res.status(403).json({error:'media is not owned by this account'})}const r=await pool.query('INSERT INTO social_posts(author_id,text,visibility,media_id,media_type) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.user.sub,text,visibility,mediaId,mediaType]);res.status(201).json({postId:String(r.rows[0].id)})}catch(e){console.error('social create post',e);res.status(500).json({error:'post creation failed'})}});
  app.delete('/api/social/posts/:id',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);const r=await pool.query('DELETE FROM social_posts WHERE id=$1 AND author_id=$2 RETURNING id',[id,req.user.sub]);if(!r.rows[0])return res.status(404).json({error:'post not found'});res.json({ok:true})}catch(e){res.status(500).json({error:'post deletion failed'})}});
  app.post('/api/social/posts/:id/like',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);if(!Number.isInteger(id)||!(await visibleSocialPost(id,req.user.sub)))return res.status(404).json({error:'post not found'});const x=await pool.query('SELECT 1 FROM social_post_likes WHERE post_id=$1 AND user_id=$2',[id,req.user.sub]);if(x.rowCount)await pool.query('DELETE FROM social_post_likes WHERE post_id=$1 AND user_id=$2',[id,req.user.sub]);else await pool.query('INSERT INTO social_post_likes(post_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,req.user.sub]);const c=await pool.query('SELECT COUNT(*)::int count FROM social_post_likes WHERE post_id=$1',[id]);res.json({liked:!x.rowCount,likeCount:c.rows[0].count})}catch(e){res.status(500).json({error:'like failed'})}});
  app.get('/api/social/posts/:id/likes',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);if(!(await visibleSocialPost(id,req.user.sub)))return res.status(404).json({error:'post not found'});const r=await pool.query('SELECT u.id,u.username,u.display_name FROM social_post_likes l JOIN users u ON u.id=l.user_id WHERE l.post_id=$1 ORDER BY l.created_at DESC LIMIT 100',[id]);res.json({users:r.rows.map(x=>({id:String(x.id),username:x.username,displayName:x.display_name}))})}catch(e){res.status(500).json({error:'likes lookup failed'})}});
  app.get('/api/social/posts/:id/comments',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);if(!(await visibleSocialPost(id,req.user.sub)))return res.status(404).json({error:'post not found'});const r=await pool.query('SELECT c.id,c.text,EXTRACT(EPOCH FROM c.created_at)*1000 timestamp,u.id author_id,u.username,u.display_name FROM social_post_comments c JOIN users u ON u.id=c.author_id WHERE c.post_id=$1 ORDER BY c.created_at ASC LIMIT 200',[id]);res.json({comments:r.rows.map(x=>({id:String(x.id),text:x.text,timestamp:Number(x.timestamp),authorId:String(x.author_id),authorUsername:x.username,authorDisplayName:x.display_name}))})}catch(e){res.status(500).json({error:'comments lookup failed'})}});
  app.post('/api/social/posts/:id/comments',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);const text=typeof req.body?.text==='string'?req.body.text.trim().slice(0,1000):'';if(!text)return res.status(400).json({error:'comment text is required'});if(!(await visibleSocialPost(id,req.user.sub)))return res.status(404).json({error:'post not found'});const r=await pool.query('INSERT INTO social_post_comments(post_id,author_id,text) VALUES($1,$2,$3) RETURNING id,EXTRACT(EPOCH FROM created_at)*1000 timestamp',[id,req.user.sub,text]);const u=await pool.query('SELECT username,display_name FROM users WHERE id=$1',[req.user.sub]);res.status(201).json({comment:{id:String(r.rows[0].id),text,timestamp:Number(r.rows[0].timestamp),authorId:String(req.user.sub),authorUsername:u.rows[0]?.username||'',authorDisplayName:u.rows[0]?.display_name||''}})}catch(e){res.status(500).json({error:'comment failed'})}});
  app.post('/api/social/follow/:username',auth,async(req,res)=>{try{await ensureSocialSchema();const u=await findUserByUsername(req.params.username.trim().toLowerCase().replace(/^@+/,''));if(!u)return res.status(404).json({error:'user not found'});if(String(u.id)===String(req.user.sub))return res.status(400).json({error:'cannot follow yourself'});const b=await pool.query('SELECT 1 FROM blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1)',[req.user.sub,u.id]);if(b.rowCount)return res.status(403).json({error:'follow unavailable'});await pool.query('INSERT INTO social_follows(follower_id,followed_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.sub,u.id]);res.status(201).json({following:true})}catch(e){res.status(500).json({error:'follow failed'})}});
  app.delete('/api/social/follow/:username',auth,async(req,res)=>{try{await ensureSocialSchema();const u=await findUserByUsername(req.params.username.trim().toLowerCase().replace(/^@+/,''));if(!u)return res.status(404).json({error:'user not found'});await pool.query('DELETE FROM social_follows WHERE follower_id=$1 AND followed_id=$2',[req.user.sub,u.id]);res.json({following:false})}catch(e){res.status(500).json({error:'unfollow failed'})}});
  app.get('/api/social/media/:id',auth,async(req,res)=>{try{await ensureSocialSchema();const id=Number(req.params.id);const r=await pool.query(`SELECT mm.mime_type,mm.data FROM message_media mm JOIN social_posts p ON p.media_id=mm.id WHERE mm.id=$1 AND (p.author_id=$2 OR p.visibility='PUBLIC' OR (p.visibility='FRIENDS_ONLY' AND EXISTS(SELECT 1 FROM friendships f WHERE ((f.user_id=p.author_id AND f.friend_id=$2) OR (f.user_id=$2 AND f.friend_id=p.author_id)) AND f.status='accepted'))) AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=$2 AND b.blocked_id=p.author_id) OR (b.blocker_id=p.author_id AND b.blocked_id=$2)) LIMIT 1`,[id,req.user.sub]);if(!r.rows[0])return res.status(404).json({error:'media not found'});res.set('Cache-Control','private,max-age=3600');res.type(r.rows[0].mime_type);res.send(r.rows[0].data)}catch(e){res.status(500).json({error:'social media fetch failed'})}});
"""
    i=s.rfind('\n}')
    if i<0: raise SystemExit('socialRoutes closing brace missing')
    p.write_text(s[:i]+add+s[i:])
PY

cat > app/src/main/java/com/fynx/app/ui/FynxRemoteSocialClient.kt <<'EOF'
package com.fynx.app.ui
import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject
object FynxRemoteSocialClient {
    data class RemotePost(val id:String,val authorId:String,val authorUsername:String,val authorDisplayName:String,val text:String,val visibility:String,val mediaId:String?,val mediaType:String?,val mediaUrl:String?,val timestamp:Long,val likeCount:Int,val commentCount:Int,val likedByCurrentUser:Boolean,val followedByCurrentUser:Boolean)
    data class RemoteComment(val id:String,val text:String,val timestamp:Long,val authorId:String,val authorUsername:String,val authorDisplayName:String)
    data class RemoteUser(val id:String,val username:String,val displayName:String)
    suspend fun feed(c:Context)=FynxBackendClient.get(c,"/api/social/feed?limit=100").mapCatching{raw->val a=JSONObject(raw).optJSONArray("posts")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemotePost(o.optString("id"),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName"),o.optString("text"),o.optString("visibility"),o.optString("mediaId").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaType").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaUrl").takeIf{it.isNotBlank()},o.optDouble("timestamp").toLong(),o.optInt("likeCount"),o.optInt("commentCount"),o.optBoolean("likedByCurrentUser"),o.optBoolean("followedByCurrentUser")))}}}
    suspend fun createPost(c:Context,text:String,visibility:FynxPostVisibility,uri:Uri?)=runCatching{val media=uri?.let{val mime=c.contentResolver.getType(it)?.lowercase() ?: "";val type=when{mime.startsWith("image/")->"image";mime.startsWith("video/")->"video";else->throw IllegalArgumentException("Select an image or video.")};FynxProductionMessaging.uploadMedia(c,it,mime).getOrThrow() to type};val body=JSONObject().apply{put("text",text.trim());put("visibility",visibility.name);put("mediaId",media?.first?.id?:JSONObject.NULL);put("mediaType",media?.second?:JSONObject.NULL)};FynxBackendClient.postJson(c,"/api/social/posts",body.toString()).getOrThrow();Unit}
    suspend fun like(c:Context,id:String)=FynxBackendClient.postJson(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/like","{}").mapCatching{val o=JSONObject(it);o.optBoolean("liked") to o.optInt("likeCount")}
    suspend fun comments(c:Context,id:String)=FynxBackendClient.get(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/comments").mapCatching{raw->val a=JSONObject(raw).optJSONArray("comments")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName")))}}}
    suspend fun addComment(c:Context,id:String,text:String)=FynxBackendClient.postJson(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/comments",JSONObject().put("text",text.trim()).toString()).mapCatching{val o=JSONObject(it).getJSONObject("comment");RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName"))}
    suspend fun likes(c:Context,id:String)=FynxBackendClient.get(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/likes").mapCatching{raw->val a=JSONObject(raw).optJSONArray("users")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteUser(o.optString("id"),o.optString("username"),o.optString("displayName")))}}}
    suspend fun follow(c:Context,username:String,following:Boolean):Result<Boolean>{val p="/api/social/follow/${java.net.URLEncoder.encode(username.removePrefix("@"),"UTF-8")}";return if(following)FynxBackendClient.delete(c,p).map{false}else FynxBackendClient.postJson(c,p,"{}").map{true}}
    suspend fun deletePost(c:Context,id:String)=FynxBackendClient.delete(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}").map{Unit}
}
EOF

cat > app/src/main/java/com/fynx/app/ui/FynxRemoteHomeSocialPanel.kt <<'EOF'
package com.fynx.app.ui
import android.graphics.BitmapFactory
import android.net.Uri
import android.view.ViewGroup
import android.widget.MediaController
import android.widget.VideoView
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.TimeUnit
@Composable fun FynxRemoteHomeSocialPanel(currentUsername:String,onOpenFindPeople:()->Unit){
    val c=LocalContext.current;val scope=rememberCoroutineScope();var posts by remember{mutableStateOf<List<FynxRemoteSocialClient.RemotePost>>(emptyList())};var loading by remember{mutableStateOf(true)};var error by remember{mutableStateOf<String?>(null)};var compose by remember{mutableStateOf(false)};var media by remember{mutableStateOf<Uri?>(null)};var text by remember{mutableStateOf("")};var visibility by remember{mutableStateOf(FynxPostVisibility.PUBLIC)};var busy by remember{mutableStateOf(false)};var comments by remember{mutableStateOf<FynxRemoteSocialClient.RemotePost?>(null)};var likes by remember{mutableStateOf<FynxRemoteSocialClient.RemotePost?>(null)}
    val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){media=it};fun reload(){scope.launch{loading=true;FynxRemoteSocialClient.feed(c).onSuccess{posts=it;error=null}.onFailure{error=it.message?:"Unable to load your feed."};loading=false}};LaunchedEffect(Unit){reload()}
    Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Your feed",style=MaterialTheme.typography.titleMedium);Text("Real posts from your FYNX network",style=MaterialTheme.typography.bodySmall)};Row{IconButton(onClick=::reload){Icon(Icons.Default.Refresh,"Refresh feed")};IconButton(onClick={compose=true}){Icon(Icons.Default.Add,"Create post")}}};if(loading)LinearProgressIndicator(Modifier.fillMaxWidth());error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(!loading&&posts.isEmpty()&&error==null)EmptyHomeCard("Your feed is ready","There are no visible posts yet. Create a post or find real people to build your FYNX circle.","Find People",onOpenFindPeople);posts.forEach{p->RemotePostCard(p,currentUsername,{id->scope.launch{FynxRemoteSocialClient.like(c,id).onSuccess{l,n->posts=posts.map{if(it.id==id)it.copy(likedByCurrentUser=l,likeCount=n)else it}}}},{comments=p},{likes=p},{following->scope.launch{FynxRemoteSocialClient.follow(c,p.authorUsername,following).onSuccess{v->posts=posts.map{if(it.authorUsername.equals(p.authorUsername,true))it.copy(followedByCurrentUser=v)else it}}}},{scope.launch{FynxRemoteSocialClient.deletePost(c,p.id).onSuccess{posts=posts.filterNot{it.id==p.id}}}})}}
    }
    if(compose)AlertDialog(onDismissRequest={if(!busy){compose=false;media=null}},title={Text("Create a post")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(text,{text=it.take(4000)},Modifier.fillMaxWidth(),minLines=3,maxLines=7,placeholder={Text("Share something with your FYNX circle…")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick={picker.launch("image/*")},Modifier.weight(1f)){Text("Photo")};OutlinedButton(onClick={picker.launch("video/*")},Modifier.weight(1f)){Text("Video")}};if(media!=null)Text("Media selected",style=MaterialTheme.typography.bodySmall);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(visibility==FynxPostVisibility.PUBLIC,{visibility=FynxPostVisibility.PUBLIC},label={Text("Public")});FilterChip(visibility==FynxPostVisibility.FRIENDS_ONLY,{visibility=FynxPostVisibility.FRIENDS_ONLY},label={Text("Friends")})}}},confirmButton={Button(enabled=!busy,onClick={scope.launch{busy=true;FynxRemoteSocialClient.createPost(c,text,visibility,media).onSuccess{compose=false;text="";media=null;reload()}.onFailure{error=it.message?:"Post failed."};busy=false}}){Text(if(busy)"Publishing…"else"Post")}},dismissButton={TextButton(enabled=!busy,onClick={compose=false;media=null}){Text("Cancel")}});comments?.let{p->CommentsDialog(p){comments=null}};likes?.let{p->LikesDialog(p){likes=null}}
}
@Composable private fun RemotePostCard(p:FynxRemoteSocialClient.RemotePost,currentUsername:String,onLike:(String)->Unit,onComment:()->Unit,onLikes:()->Unit,onFollow:(Boolean)->Unit,onDelete:()->Unit){val mine=p.authorUsername.equals(currentUsername.removePrefix("@"),true);Card(Modifier.fillMaxWidth(),shape=FynxDesign.LargeCardShape,colors=CardDefaults.cardColors(FynxDesign.Surface),border=BorderStroke(1.dp,FynxDesign.Outline.copy(alpha=.55f))){Column{Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){FynxAvatar(p.authorUsername,Modifier.size(46.dp).clip(CircleShape));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(p.authorDisplayName.ifBlank{p.authorUsername},style=MaterialTheme.typography.titleSmall);Text("@${p.authorUsername.removePrefix("@")} • ${relative(p.timestamp)}",style=MaterialTheme.typography.labelSmall)};if(mine)IconButton(onClick=onDelete){Icon(Icons.Default.DeleteOutline,"Delete post")}else TextButton(onClick={onFollow(p.followedByCurrentUser)}){Text(if(p.followedByCurrentUser)"Following"else"Follow")}};if(p.text.isNotBlank())Text(p.text,Modifier.padding(horizontal=14.dp,vertical=4.dp));p.mediaUrl?.let{RemoteSocialMedia(it,p.mediaType)};Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){TextButton(onClick={onLike(p.id)}){Icon(if(p.likedByCurrentUser)Icons.Default.Favorite else Icons.Default.FavoriteBorder,null);Text(p.likeCount.toString())};TextButton(onClick=onLikes){Text("Likes")};TextButton(onClick=onComment){Icon(Icons.Default.ChatBubbleOutline,null);Text(p.commentCount.toString())}}}}}
@Composable private fun RemoteSocialMedia(path:String,type:String?){val c=LocalContext.current;var f by remember(path){mutableStateOf<File?>(null)};LaunchedEffect(path){f=withContext(Dispatchers.IO){download(c,path,type)}};if(f==null)Box(Modifier.fillMaxWidth().height(220.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}else if(type=="video")AndroidView(factory={ctx->VideoView(ctx).apply{layoutParams=ViewGroup.LayoutParams(-1,640);setMediaController(MediaController(ctx));setVideoURI(Uri.fromFile(f));setOnPreparedListener{it.isLooping=true;start()}}},Modifier.fillMaxWidth().height(320.dp))else{var b by remember(f){mutableStateOf<android.graphics.Bitmap?>(null)};LaunchedEffect(f){b=withContext(Dispatchers.IO){runCatching{BitmapFactory.decodeFile(f!!.absolutePath)}.getOrNull()}};b?.let{Image(it.asImageBitmap(),"Post media",Modifier.fillMaxWidth().heightIn(min=240.dp,max=520.dp),contentScale=ContentScale.Crop)}}}
private fun download(c:android.content.Context,path:String,type:String?):File?=runCatching{val x=(URL(FynxBackendClient.baseUrl(c)+path).openConnection() as HttpURLConnection).apply{connectTimeout=10000;readTimeout=20000;setRequestProperty("Authorization","Bearer ${FynxBackendClient.accessToken(c)?:""}")};try{if(x.responseCode !in 200..299)return null;val f=File.createTempFile("fynx_social_",if(type=="video")".mp4"else".jpg",c.cacheDir);x.inputStream.use{a->FileOutputStream(f).use{b->a.copyTo(b)}};f}finally{x.disconnect()}}.getOrNull()
@Composable private fun CommentsDialog(p:FynxRemoteSocialClient.RemotePost,onClose:()->Unit){val c=LocalContext.current;val scope=rememberCoroutineScope();var list by remember(p.id){mutableStateOf<List<FynxRemoteSocialClient.RemoteComment>>(emptyList())};var text by remember{mutableStateOf("")};LaunchedEffect(p.id){FynxRemoteSocialClient.comments(c,p.id).onSuccess{list=it}};AlertDialog(onDismissRequest=onClose,title={Text("Comments")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){list.forEach{x->Column{Text(x.authorDisplayName.ifBlank{x.authorUsername});Text(x.text);Text(relative(x.timestamp),style=MaterialTheme.typography.labelSmall)}};if(list.isEmpty())Text("No comments yet.");OutlinedTextField(text,{text=it.take(1000)},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text("Write a comment…")})}},confirmButton={TextButton(onClick={if(text.isNotBlank())scope.launch{FynxRemoteSocialClient.addComment(c,p.id,text).onSuccess{list=list+it;text=""}}}){Text("Comment")}},dismissButton={TextButton(onClick=onClose){Text("Close")}})}
@Composable private fun LikesDialog(p:FynxRemoteSocialClient.RemotePost,onClose:()->Unit){val c=LocalContext.current;var list by remember(p.id){mutableStateOf<List<FynxRemoteSocialClient.RemoteUser>>(emptyList())};LaunchedEffect(p.id){FynxRemoteSocialClient.likes(c,p.id).onSuccess{list=it}};AlertDialog(onDismissRequest=onClose,title={Text("People who liked this")},text={LazyColumn{items(list){u->Row(Modifier.fillMaxWidth().padding(7.dp),verticalAlignment=Alignment.CenterVertically){FynxAvatar(u.username,Modifier.size(38.dp));Spacer(Modifier.width(10.dp));Column{Text(u.displayName.ifBlank{u.username});Text("@${u.username.removePrefix("@")}",style=MaterialTheme.typography.labelSmall)}}}}},confirmButton={TextButton(onClick=onClose){Text("Close")}})}
private fun relative(t:Long):String{val m=TimeUnit.MILLISECONDS.toMinutes((System.currentTimeMillis()-t).coerceAtLeast(0));return when{m<1->"now";m<60->"${m}m";m<1440->"${m/60}h";else->"${m/1440}d"}}
EOF
python3 - <<'PY'
from pathlib import Path
p=Path('app/src/main/java/com/fynx/app/ui/HomePanel.kt');s=p.read_text();a=s.find('        item { SectionHeader("Your feed", "Find people", onOpenFindPeople) }');b=s.find('        item { SectionHeader("Your conversations", "Open Chats", onOpenChats)',a)
if a>=0 and b>=0:p.write_text(s[:a]+'        item { FynxRemoteHomeSocialPanel(currentUsername = displayUsername, onOpenFindPeople = onOpenFindPeople) }\n'+s[b:])
else: raise SystemExit('Home feed markers not found')
PY
