#!/usr/bin/env python3
"""Generate a single evidence index for the FYNX certification pipeline."""
from __future__ import annotations
import os
from pathlib import Path

ROOT = Path(".")
OUT = ROOT / "fynx-investigation-report"
OUT.mkdir(parents=True, exist_ok=True)
sha = os.environ.get("GITHUB_SHA", "local")
run_id = os.environ.get("GITHUB_RUN_ID", "local")
workflow = os.environ.get("GITHUB_WORKFLOW", "unknown")

checks = [
    ("Network transport architecture", "scripts/verify_network_transport_architecture.py"),
    ("Production backend reachability", "scripts/verify_production_backend_reachability.mjs"),
    ("FYNX journey contract", "scripts/verify_fynx_journey.py"),
    ("Visual regression", "scripts/verify_visual_regression.py"),
    ("Accessibility / screen safety", "scripts/verify_accessibility_screen_safety.py"),
    ("Responsive certification", "scripts/verify_large_badge15_responsive.py"),
    ("APK ↔ commit certification", "scripts/verify_large_badge16_apk_commit_runtime.py"),
    ("Maestro launch/auth journey", ".maestro/fynx-launch-and-auth.yaml"),
]
lines = [
    "# FYNX Investigation Report",
    "",
f"    - Commit: {sha}",
f"    - Workflow: {workflow}",
f"    - Run: {run_id}",
    "",
    "This report indexes certification evidence generated by the same CI run.",
    "It does not manufacture application data and does not treat source presence as runtime proof.",
    "",
    "## Certification layers",
]
for name, path in checks:
    exists = (ROOT / path).is_file()
    lines.append(f"- {'PRESENT' if exists else 'MISSING'} — {name}: `{path}`")
lines += [
    "",
    "## Runtime evidence expected from this run",
    "- `fynx-runtime-screenshots/` — emulator screenshots and UI hierarchies",
    "- `fynx-accessibility-certification/` — accessibility/screen-safety evidence",
    "- `fynx-responsive-certification/` — small/medium/large viewport certification",
    "- `fynx-visual-regression/` — approved-baseline comparison results",
    "- `fynx-maestro-results/` — Maestro journey output",
    "- `fynx-apk-certification/` — exact APK/commit verification",
    "",
    "## External-device status",
    "- Firebase Test Lab/Robo: integration exists; current full-runtime certification uses the existing emulator when Test Lab access is blocked.",
    "- BrowserStack: real-device execution runs only when credentials are configured; readiness is recorded instead of fabricating device evidence.",
    "",
    "## Interpretation rule",
    "- A GREEN build alone is not proof that a feature works.",
    "- Runtime, APK identity, visual, accessibility and journey evidence must be considered together.",
    "",
]
(OUT / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("\n".join(lines))