notification_push = read("backend/notificationPush.js")
notification_bootstrap = read("backend/notificationBootstrap.js")
status_routes = read("backend/statusInteractionRoutes.js")
social_routes = read("backend/socialRoutes.js")
home = read("app/src/main/java/com/fynx/app/ui/FynxRemoteHomeSocialPanel.kt")
timeline = read("app/src/main/java/com/fynx/app/ui/FynxStatusTimelinePanel.kt")
messages = read("backend/server.js")

check("two-real-user status visibility path", "FynxStatusClient.list(context)" in timeline and "expires_at > NOW()" in status_routes)
check("two-real-user post visibility path", "FynxRemoteSocialClient.feedPage" in home and "visibility" in social_routes)
check("two-real-user block enforcement", "blocks" in social_routes and "blocks" in status_routes and "blocks" in messages and "conversation unavailable" in messages)
check("production app is not in preview mode", "FYNX_PREVIEW_MODE = false" in app)
check("signed-in gate protects the production surface", "AuthState.SIGNED_IN" in app)
check("backend client owns authenticated API access", "hasAccessToken" in client and "Authorization" in client)
check("logout clears the secure local token and session state", "fun clear(context: Context)" in auth and "FynxSecureTokenStore.save(context, null)" in auth)
check("profile uses real backend identity and counts", "FynxProfileRemoteClient" in profile and "followerCount" in profile and "followingCount" in profile)
# Counts on another user's profile are allowed when the backend explicitly
# returns them. What must remain prohibited is a rendered follower/following
# member list that bypasses the server visibility decision.
check("other-user profile does not expose private follower/following lists", not re.search(r"(?:followers?|following)\\s+(?:list|members?|user|people|names)", other_profile, re.IGNORECASE))
check("profile privacy is enforced server-side", "connectionsVisible:self" in profile_api and "privacy" in profile_api.lower())
check("private chat is connected to authenticated backend flow", ("FynxProductionMessaging" in chat and "sendText" in chat and "history" in chat) or ("FynxBackendClient" in chat and ("send" in chat.lower() or "message" in chat.lower())))
check("marketplace is remote/backend-backed", "FynxMarketplaceClient.listings" in market and "FynxMarketplaceClient.createListing" in market)
check("marketplace transaction protection remains server-side", all(x in market_api for x in ["marketplace_orders", "PAYMENT_PENDING", "DISPUTED", "marketplace_order_disputes", "payout:'not_released'"]))
check("group membership and messages are server-authoritative", all(x in group_api for x in ["fynx_group_members", "fynx_group_messages", "app.get('/api/groups/:groupId/messages'", "app.post('/api/groups/:groupId/messages'", "jwt.verify"]))
check("friend/social actions are backend-backed", "registerSocialRoutes" in social_api and all(x in social_api for x in ["/api/friends", "/api/friends/request", "friendships"]))
check("privacy settings surface is connected", "FynxPrivacySettingsPanel" in app and "FynxPrivacySettings" in privacy)
check("deep-link parser and live activity routing are connected", "FynxDeepLinkParser.parse" in main and all(x in app for x in ["FynxDeepLinkDestination.Profile", "FynxDeepLinkDestination.Chat", "FynxDeepLinkDestination.Group", "FynxDeepLinkDestination.Marketplace"]) and all(x in deep_link for x in ["fun parse", "profileWebLink", "chatWebLink", "groupWebLink", "marketplaceWebLink"]))
check("FCM token registration is authenticated and account-scoped", "hasAccessToken" in fcm_client and "/api/notification-devices" in fcm_client)
check("FCM service handles token refresh and incoming data", "onNewToken" in fcm_service and "onMessageReceived" in fcm_service)
check("notification device storage is user-scoped", "user_id" in notification_devices and "REFERENCES users(id)" in notification_devices)
check("notification sender keeps credentials server-side", "FIREBASE_SERVICE_ACCOUNT_JSON" in notification_push and "FIREBASE_PRIVATE_KEY" in notification_push and "firebase" in notification_push.lower())
check("notification bootstrap is idempotent integration glue", "async function patchOnce" in notification_bootstrap and "changed = false" in notification_bootstrap and "patches" in notification_bootstrap)

client_sources = [p.read_text(encoding="utf-8") for p in (ROOT / "app/src/main/java/com/fynx/app/ui").glob("*.kt")]
all_client = "\n".join(client_sources)