package com.fynx.app.ui
import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject
object FynxRemoteSocialClient {
    data class RemotePost(val id:String,val authorId:String,val authorUsername:String,val authorDisplayName:String,val text:String,val visibility:String,val mediaId:String?,val mediaType:String?,val mediaUrl:String?,val timestamp:Long,val likeCount:Int,val commentCount:Int,val likedByCurrentUser:Boolean,val followedByCurrentUser:Boolean)
    data class RemoteComment(val id:String,val text:String,val timestamp:Long,val authorId:String,val authorUsername:String,val authorDisplayName:String)
    data class RemoteUser(val id:String,val username:String,val displayName:String)
    suspend fun feed(c:Context)=FynxBackendClient.get(c,"/api/social/feed?limit=100").mapCatching{raw->val a=JSONObject(raw).optJSONArray("posts")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemotePost(o.optString("id"),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName"),o.optString("text"),o.optString("visibility"),o.optString("mediaId").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaType").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaUrl").takeIf{it.isNotBlank()},o.optDouble("timestamp").toLong(),o.optInt("likeCount"),o.optInt("commentCount"),o.optBoolean("likedByCurrentUser"),o.optBoolean("followedByCurrentUser")))}}}
    suspend fun createPost(c:Context,text:String,visibility:FynxPostVisibility,uri:Uri?)=runCatching{val media=uri?.let{val mime=c.contentResolver.getType(it)?.lowercase() ?: "";val type=when{mime.startsWith("image/")->"image";mime.startsWith("video/")->"video";else->throw IllegalArgumentException("Select an image or video.")};FynxProductionMessaging.uploadMedia(c,it,mime).getOrThrow() to type};val body=JSONObject().apply{put("text",text.trim());put("visibility",visibility.name);put("mediaId",media?.first?.id?:JSONObject.NULL);put("mediaType",media?.second?:JSONObject.NULL)};FynxBackendClient.postJson(c,"/api/social/posts",body.toString()).getOrThrow();Unit}
    suspend fun like(c:Context,id:String)=FynxBackendClient.postJson(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/like","{}").mapCatching{val o=JSONObject(it);o.optBoolean("liked") to o.optInt("likeCount")}
    suspend fun comments(c:Context,id:String)=FynxBackendClient.get(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/comments").mapCatching{raw->val a=JSONObject(raw).optJSONArray("comments")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName")))}}}
    suspend fun addComment(c:Context,id:String,text:String)=FynxBackendClient.postJson(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/comments",JSONObject().put("text",text.trim()).toString()).mapCatching{val o=JSONObject(it).getJSONObject("comment");RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName"))}
    suspend fun likes(c:Context,id:String)=FynxBackendClient.get(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}/likes").mapCatching{raw->val a=JSONObject(raw).optJSONArray("users")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteUser(o.optString("id"),o.optString("username"),o.optString("displayName")))}}}
    suspend fun follow(c:Context,username:String,following:Boolean):Result<Boolean>{val p="/api/social/follow/${java.net.URLEncoder.encode(username.removePrefix("@"),"UTF-8")}";return if(following)FynxBackendClient.delete(c,p).map{false}else FynxBackendClient.postJson(c,p,"{}").map{true}}
    suspend fun deletePost(c:Context,id:String)=FynxBackendClient.delete(c,"/api/social/posts/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"))}").map{Unit}
}
