package com.fynx.app.ui

import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject

object FynxRemoteSocialClient {
    data class RemotePost(val id: String,val authorId: String,val authorUsername: String,val authorDisplayName: String,val text: String,val visibility: String,val mediaId: String?,val mediaType: String?,val mediaUrl: String?,val timestamp: Long,val likeCount: Int,val commentCount: Int,val likedByCurrentUser: Boolean,val followedByCurrentUser: Boolean)
    data class RemoteComment(val id: String,val text: String,val timestamp: Long,val authorId: String,val authorUsername: String,val authorDisplayName: String)
    data class RemoteUser(val id: String,val username: String,val displayName: String)
    data class MarketplaceListing(val id:String,val sellerId:String,val sellerUsername:String,val sellerDisplayName:String,val storeName:String,val title:String,val description:String,val price:Double,val currency:String,val category:String,val condition:String,val quantity:Int,val location:String,val deliveryAvailable:Boolean,val pickupAvailable:Boolean,val deliveryFee:Double?,val mediaIds:List<String>,val active:Boolean=true)
    data class MarketplaceOrder(val id:String,val buyerId:String,val sellerId:String,val listingId:String,val quantity:Int,val unitPrice:Double,val deliveryFee:Double,val totalAmount:Double,val currency:String,val productTitle:String,val sellerUsername:String?,val status:String,val trackingReference:String?)

    suspend fun feed(context: Context): Result<List<RemotePost>> = FynxBackendClient.get(context,"/api/social/feed?limit=100").mapCatching { raw -> val a=JSONObject(raw).optJSONArray("posts")?:JSONArray(); buildList { for(i in 0 until a.length()){ val o=a.getJSONObject(i); add(RemotePost(o.optString("id"),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName"),o.optString("text"),o.optString("visibility"),o.optString("mediaId").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaType").takeIf{it.isNotBlank()&&it!="null"},o.optString("mediaUrl").takeIf{it.isNotBlank()},o.optDouble("timestamp").toLong(),o.optInt("likeCount"),o.optInt("commentCount"),o.optBoolean("likedByCurrentUser"),o.optBoolean("followedByCurrentUser"))) } }

    suspend fun createPost(context: Context,text:String,visibility:FynxPostVisibility,uri:Uri?):Result<Unit> = runCatching { val media=uri?.let{ val mime=mediaMimeType(context,it); val type=when{mime.startsWith("image/")->"image";mime.startsWith("video/")->"video";mime.startsWith("audio/")->"audio";else->throw IllegalArgumentException("Select an image, video or audio.")};FynxProductionMessaging.uploadMedia(context,it,mime).getOrThrow() to type }; val body=JSONObject().apply{put("text",text.trim());put("visibility",visibility.name);put("mediaId",media?.first?.id?:JSONObject.NULL);put("mediaType",media?.second?:JSONObject.NULL)};FynxBackendClient.postJson(context,"/api/social/posts",body.toString()).getOrThrow();Unit }

    private fun mediaMimeType(context:Context,uri:Uri):String { context.contentResolver.getType(uri)?.lowercase()?.takeIf{it.isNotBlank()}?.let{return it};val p=uri.path?.lowercase().orEmpty();return when{p.endsWith(".jpg")||p.endsWith(".jpeg")->"image/jpeg";p.endsWith(".png")->"image/png";p.endsWith(".webp")->"image/webp";p.endsWith(".heic")||p.endsWith(".heif")->"image/heif";p.endsWith(".mp4")->"video/mp4";p.endsWith(".3gp")->"video/3gpp";p.endsWith(".webm")->"video/webm";p.endsWith(".m4a")->"audio/mp4";p.endsWith(".aac")->"audio/aac";p.endsWith(".mp3")->"audio/mpeg";p.endsWith(".wav")->"audio/wav";else->""} }

    suspend fun createMarketplaceAd(context:Context,listingId:String,title:String,description:String,storeName:String,price:Double,currency:String,mediaId:String?):Result<Unit>{val priceText="${currency.trim().uppercase()} ${String.format(java.util.Locale.US,"%,.2f",price)}";val text="[FYNX_MARKETPLACE_AD]\n🛍️ ${title.trim().take(120)}\nPrice: $priceText\nStore: ${storeName.trim().take(120)}\n${description.trim().take(1000)}\nListing ID: $listingId";val b=JSONObject().apply{put("text",text.take(4000));put("visibility","PUBLIC");put("mediaId",mediaId?:JSONObject.NULL);put("mediaType",if(mediaId!=null)"image" else JSONObject.NULL)};return FynxBackendClient.postJson(context,"/api/social/posts",b.toString()).map{Unit}}

    suspend fun listings(context:Context,query:String="",category:String="All",seller:String=""):Result<List<MarketplaceListing>> = FynxBackendClient.get(context,"/api/marketplace/listings?q=${java.net.URLEncoder.encode(query,"UTF-8")}&category=${java.net.URLEncoder.encode(category,"UTF-8")}&seller=${java.net.URLEncoder.encode(seller.removePrefix("@"),"UTF-8")}").mapCatching{raw->val a=JSONObject(raw).optJSONArray("listings")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);val ids=o.optJSONArray("media_ids")?:JSONArray();add(MarketplaceListing(o.optString("id"),o.optString("seller_id"),o.optString("seller_username"),o.optString("seller_display_name"),o.optString("store_name"),o.optString("title"),o.optString("description"),o.optDouble("price"),o.optString("currency","NGN"),o.optString("category"),o.optString("condition","NEW"),o.optInt("quantity"),o.optString("location"),o.optBoolean("delivery_available"),o.optBoolean("pickup_available",true),if(o.isNull("delivery_fee"))null else o.optDouble("delivery_fee"),buildList{for(j in 0 until ids.length())add(ids.get(j).toString())})}}}

    suspend fun myListings(context:Context):Result<List<MarketplaceListing>> = FynxBackendClient.get(context,"/api/marketplace/my-listings").mapCatching{parseListings(it)}
    private fun parseListings(raw:String):List<MarketplaceListing>{val a=JSONObject(raw).optJSONArray("listings")?:JSONArray();return buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);val ids=o.optJSONArray("media_ids")?:JSONArray();add(MarketplaceListing(o.optString("id"),o.optString("seller_id"),o.optString("seller_username"),o.optString("seller_display_name"),o.optString("store_name"),o.optString("title"),o.optString("description"),o.optDouble("price"),o.optString("currency","NGN"),o.optString("category"),o.optString("condition","NEW"),o.optInt("quantity"),o.optString("location"),o.optBoolean("delivery_available"),o.optBoolean("pickup_available",true),if(o.isNull("delivery_fee"))null else o.optDouble("delivery_fee"),buildList{for(j in 0 until ids.length())add(ids.get(j).toString())}),o.optBoolean("active",true))}}}

    suspend fun createMarketplaceListing(context:Context,title:String,description:String,storeName:String,price:Double,currency:String,category:String,condition:String,quantity:Int,location:String,deliveryAvailable:Boolean,pickupAvailable:Boolean,deliveryFee:Double?,mediaUris:List<Uri>):Result<MarketplaceListing?> = runCatching{require(title.trim().length>=2);require(description.trim().length>=5);require(price>0);require(quantity>=0);require(mediaUris.isNotEmpty());val ids=mediaUris.map{FynxProductionMessaging.uploadMedia(context,it,mediaMimeType(context,it)).getOrThrow().id};val body=JSONObject().apply{put("title",title.trim());put("description",description.trim());put("storeName",storeName.trim());put("price",price);put("currency",currency.trim().uppercase());put("category",category);put("condition",condition);put("quantity",quantity);put("location",location.trim());put("deliveryAvailable",deliveryAvailable);put("pickupAvailable",pickupAvailable);put("deliveryFee",deliveryFee?:JSONObject.NULL);put("mediaIds",JSONArray(ids))};val raw=FynxBackendClient.postJson(context,"/api/marketplace/listings",body.toString()).getOrThrow();val id=JSONObject(raw).getJSONObject("listing").optString("id"); listings(context).getOrNull()?.firstOrNull{it.id==id} }

    suspend fun deleteMarketplaceListing(context:Context,id:String):Result<Unit> = FynxBackendClient.delete(context,"/api/marketplace/listings/${id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid listing id"))}").map{Unit}
    suspend fun createMarketplaceOrder(context:Context,listingId:String,quantity:Int):Result<MarketplaceOrder> = FynxBackendClient.postJson(context,"/api/marketplace/orders",JSONObject().apply{put("listingId",listingId.toLong());put("quantity",quantity);put("orderId",java.util.UUID.randomUUID().toString())}.toString()).mapCatching{parseOrder(JSONObject(it).getJSONObject("order"))}
    suspend fun orders(context:Context):Result<List<MarketplaceOrder>> = FynxBackendClient.get(context,"/api/marketplace/orders").mapCatching{val a=JSONObject(it).optJSONArray("orders")?:JSONArray();buildList{for(i in 0 until a.length())add(parseOrder(a.getJSONObject(i)))}}
    private fun parseOrder(o:JSONObject)=MarketplaceOrder(o.optString("id"),o.optString("buyerId"),o.optString("sellerId"),o.optString("listingId"),o.optInt("quantity"),o.optDouble("unitPrice"),o.optDouble("deliveryFee"),o.optDouble("totalAmount"),o.optString("currency"),o.optJSONObject("product")?.optString("title").orEmpty(),o.optString("product").takeIf{it.isNotBlank()},o.optString("status"),o.optString("trackingReference").takeIf{it.isNotBlank()})
    suspend fun cancelMarketplaceOrder(context:Context,id:String):Result<Unit> = FynxBackendClient.postJson(context,"/api/marketplace/orders/$id/cancel","{}").map{Unit}
    suspend fun disputeMarketplaceOrder(context:Context,id:String,reason:String,details:String):Result<Unit> = FynxBackendClient.postJson(context,"/api/marketplace/orders/$id/disputes",JSONObject().apply{put("reason",reason);put("details",details)}.toString()).map{Unit}
    suspend fun reviewMarketplaceOrder(context:Context,id:String,rating:Int,comment:String):Result<Unit> = FynxBackendClient.postJson(context,"/api/marketplace/orders/$id/review",JSONObject().apply{put("rating",rating);put("comment",comment)}.toString()).map{Unit}

    suspend fun like(context:Context,id:String):Result<Pair<Boolean,Int>>{val postId=id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"));return FynxBackendClient.postJson(context,"/api/social/posts/$postId/like","{}").mapCatching{val o=JSONObject(it);o.optBoolean("liked") to o.optInt("likeCount")}}
    suspend fun comments(context:Context,id:String):Result<List<RemoteComment>>{val postId=id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"));return FynxBackendClient.get(context,"/api/social/posts/$postId/comments").mapCatching{val a=JSONObject(it).optJSONArray("comments")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName")))}}}}
    suspend fun addComment(context:Context,id:String,text:String):Result<RemoteComment>{val postId=id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"));return FynxBackendClient.postJson(context,"/api/social/posts/$postId/comments",JSONObject().put("text",text.trim()).toString()).mapCatching{val o=JSONObject(it).getJSONObject("comment");RemoteComment(o.optString("id"),o.optString("text"),o.optDouble("timestamp").toLong(),o.optString("authorId"),o.optString("authorUsername"),o.optString("authorDisplayName") )}}
    suspend fun likes(context:Context,id:String):Result<List<RemoteUser>>{val postId=id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"));return FynxBackendClient.get(context,"/api/social/posts/$postId/likes").mapCatching{val a=JSONObject(it).optJSONArray("users")?:JSONArray();buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(RemoteUser(o.optString("id"),o.optString("username"),o.optString("displayName")))}}}}
    suspend fun follow(context:Context,username:String,following:Boolean):Result<Boolean>{val e=java.net.URLEncoder.encode(username.trim().removePrefix("@"),"UTF-8");return if(following)FynxBackendClient.delete(context,"/api/social/follow/$e").map{false}else FynxBackendClient.postJson(context,"/api/social/follow/$e","{}").map{true}}
    suspend fun deletePost(context:Context,id:String):Result<Unit>{val postId=id.toLongOrNull()?:return Result.failure(IllegalArgumentException("invalid post id"));return FynxBackendClient.delete(context,"/api/social/posts/$postId").map{Unit}}
}
