package com.fynx.app.ui
import android.graphics.BitmapFactory
import android.net.Uri
import android.view.ViewGroup
import android.widget.MediaController
import android.widget.VideoView
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.TimeUnit
@Composable fun FynxRemoteHomeSocialPanel(currentUsername:String,onOpenFindPeople:()->Unit){
    val c=LocalContext.current;val scope=rememberCoroutineScope();var posts by remember{mutableStateOf<List<FynxRemoteSocialClient.RemotePost>>(emptyList())};var loading by remember{mutableStateOf(true)};var error by remember{mutableStateOf<String?>(null)};var compose by remember{mutableStateOf(false)};var media by remember{mutableStateOf<Uri?>(null)};var text by remember{mutableStateOf("")};var visibility by remember{mutableStateOf(FynxPostVisibility.PUBLIC)};var busy by remember{mutableStateOf(false)};var comments by remember{mutableStateOf<FynxRemoteSocialClient.RemotePost?>(null)};var likes by remember{mutableStateOf<FynxRemoteSocialClient.RemotePost?>(null)}
    val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){media=it};fun reload(){scope.launch{loading=true;FynxRemoteSocialClient.feed(c).onSuccess{posts=it;error=null}.onFailure{error=it.message?:"Unable to load your feed."};loading=false}};LaunchedEffect(Unit){reload()}
    Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Your feed",style=MaterialTheme.typography.titleMedium);Text("Real posts from your FYNX network",style=MaterialTheme.typography.bodySmall)};Row{IconButton(onClick=::reload){Icon(Icons.Default.Refresh,"Refresh feed")};IconButton(onClick={compose=true}){Icon(Icons.Default.Add,"Create post")}}};if(loading)LinearProgressIndicator(Modifier.fillMaxWidth());error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(!loading&&posts.isEmpty()&&error==null)EmptyHomeCard("Your feed is ready","There are no visible posts yet. Create a post or find real people to build your FYNX circle.","Find People",onOpenFindPeople);posts.forEach{p->RemotePostCard(p,currentUsername,{id->scope.launch{FynxRemoteSocialClient.like(c,id).onSuccess{l,n->posts=posts.map{if(it.id==id)it.copy(likedByCurrentUser=l,likeCount=n)else it}}}},{comments=p},{likes=p},{following->scope.launch{FynxRemoteSocialClient.follow(c,p.authorUsername,following).onSuccess{v->posts=posts.map{if(it.authorUsername.equals(p.authorUsername,true))it.copy(followedByCurrentUser=v)else it}}}},{scope.launch{FynxRemoteSocialClient.deletePost(c,p.id).onSuccess{posts=posts.filterNot{it.id==p.id}}}})}}
    }
    if(compose)AlertDialog(onDismissRequest={if(!busy){compose=false;media=null}},title={Text("Create a post")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(text,{text=it.take(4000)},Modifier.fillMaxWidth(),minLines=3,maxLines=7,placeholder={Text("Share something with your FYNX circle…")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick={picker.launch("image/*")},Modifier.weight(1f)){Text("Photo")};OutlinedButton(onClick={picker.launch("video/*")},Modifier.weight(1f)){Text("Video")}};if(media!=null)Text("Media selected",style=MaterialTheme.typography.bodySmall);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(visibility==FynxPostVisibility.PUBLIC,{visibility=FynxPostVisibility.PUBLIC},label={Text("Public")});FilterChip(visibility==FynxPostVisibility.FRIENDS_ONLY,{visibility=FynxPostVisibility.FRIENDS_ONLY},label={Text("Friends")})}}},confirmButton={Button(enabled=!busy,onClick={scope.launch{busy=true;FynxRemoteSocialClient.createPost(c,text,visibility,media).onSuccess{compose=false;text="";media=null;reload()}.onFailure{error=it.message?:"Post failed."};busy=false}}){Text(if(busy)"Publishing…"else"Post")}},dismissButton={TextButton(enabled=!busy,onClick={compose=false;media=null}){Text("Cancel")}});comments?.let{p->CommentsDialog(p){comments=null}};likes?.let{p->LikesDialog(p){likes=null}}
}
@Composable private fun RemotePostCard(p:FynxRemoteSocialClient.RemotePost,currentUsername:String,onLike:(String)->Unit,onComment:()->Unit,onLikes:()->Unit,onFollow:(Boolean)->Unit,onDelete:()->Unit){val mine=p.authorUsername.equals(currentUsername.removePrefix("@"),true);Card(Modifier.fillMaxWidth(),shape=FynxDesign.LargeCardShape,colors=CardDefaults.cardColors(FynxDesign.Surface),border=BorderStroke(1.dp,FynxDesign.Outline.copy(alpha=.55f))){Column{Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){FynxAvatar(p.authorUsername,Modifier.size(46.dp).clip(CircleShape));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(p.authorDisplayName.ifBlank{p.authorUsername},style=MaterialTheme.typography.titleSmall);Text("@${p.authorUsername.removePrefix("@")} • ${relative(p.timestamp)}",style=MaterialTheme.typography.labelSmall)};if(mine)IconButton(onClick=onDelete){Icon(Icons.Default.DeleteOutline,"Delete post")}else TextButton(onClick={onFollow(p.followedByCurrentUser)}){Text(if(p.followedByCurrentUser)"Following"else"Follow")}};if(p.text.isNotBlank())Text(p.text,Modifier.padding(horizontal=14.dp,vertical=4.dp));p.mediaUrl?.let{RemoteSocialMedia(it,p.mediaType)};Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){TextButton(onClick={onLike(p.id)}){Icon(if(p.likedByCurrentUser)Icons.Default.Favorite else Icons.Default.FavoriteBorder,null);Text(p.likeCount.toString())};TextButton(onClick=onLikes){Text("Likes")};TextButton(onClick=onComment){Icon(Icons.Default.ChatBubbleOutline,null);Text(p.commentCount.toString())}}}}}
@Composable private fun RemoteSocialMedia(path:String,type:String?){val c=LocalContext.current;var f by remember(path){mutableStateOf<File?>(null)};LaunchedEffect(path){f=withContext(Dispatchers.IO){download(c,path,type)}};if(f==null)Box(Modifier.fillMaxWidth().height(220.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}else if(type=="video")AndroidView(factory={ctx->VideoView(ctx).apply{layoutParams=ViewGroup.LayoutParams(-1,640);setMediaController(MediaController(ctx));setVideoURI(Uri.fromFile(f));setOnPreparedListener{it.isLooping=true;start()}}},Modifier.fillMaxWidth().height(320.dp))else{var b by remember(f){mutableStateOf<android.graphics.Bitmap?>(null)};LaunchedEffect(f){b=withContext(Dispatchers.IO){runCatching{BitmapFactory.decodeFile(f!!.absolutePath)}.getOrNull()}};b?.let{Image(it.asImageBitmap(),"Post media",Modifier.fillMaxWidth().heightIn(min=240.dp,max=520.dp),contentScale=ContentScale.Crop)}}}
private fun download(c:android.content.Context,path:String,type:String?):File?=runCatching{val x=(URL(FynxBackendClient.baseUrl(c)+path).openConnection() as HttpURLConnection).apply{connectTimeout=10000;readTimeout=20000;setRequestProperty("Authorization","Bearer ${FynxBackendClient.accessToken(c)?:""}")};try{if(x.responseCode !in 200..299)return null;val f=File.createTempFile("fynx_social_",if(type=="video")".mp4"else".jpg",c.cacheDir);x.inputStream.use{a->FileOutputStream(f).use{b->a.copyTo(b)}};f}finally{x.disconnect()}}.getOrNull()
@Composable private fun CommentsDialog(p:FynxRemoteSocialClient.RemotePost,onClose:()->Unit){val c=LocalContext.current;val scope=rememberCoroutineScope();var list by remember(p.id){mutableStateOf<List<FynxRemoteSocialClient.RemoteComment>>(emptyList())};var text by remember{mutableStateOf("")};LaunchedEffect(p.id){FynxRemoteSocialClient.comments(c,p.id).onSuccess{list=it}};AlertDialog(onDismissRequest=onClose,title={Text("Comments")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){list.forEach{x->Column{Text(x.authorDisplayName.ifBlank{x.authorUsername});Text(x.text);Text(relative(x.timestamp),style=MaterialTheme.typography.labelSmall)}};if(list.isEmpty())Text("No comments yet.");OutlinedTextField(text,{text=it.take(1000)},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text("Write a comment…")})}},confirmButton={TextButton(onClick={if(text.isNotBlank())scope.launch{FynxRemoteSocialClient.addComment(c,p.id,text).onSuccess{list=list+it;text=""}}}){Text("Comment")}},dismissButton={TextButton(onClick=onClose){Text("Close")}})}
@Composable private fun LikesDialog(p:FynxRemoteSocialClient.RemotePost,onClose:()->Unit){val c=LocalContext.current;var list by remember(p.id){mutableStateOf<List<FynxRemoteSocialClient.RemoteUser>>(emptyList())};LaunchedEffect(p.id){FynxRemoteSocialClient.likes(c,p.id).onSuccess{list=it}};AlertDialog(onDismissRequest=onClose,title={Text("People who liked this")},text={LazyColumn{items(list){u->Row(Modifier.fillMaxWidth().padding(7.dp),verticalAlignment=Alignment.CenterVertically){FynxAvatar(u.username,Modifier.size(38.dp));Spacer(Modifier.width(10.dp));Column{Text(u.displayName.ifBlank{u.username});Text("@${u.username.removePrefix("@")}",style=MaterialTheme.typography.labelSmall)}}}}},confirmButton={TextButton(onClick=onClose){Text("Close")}})}
private fun relative(t:Long):String{val m=TimeUnit.MILLISECONDS.toMinutes((System.currentTimeMillis()-t).coerceAtLeast(0));return when{m<1->"now";m<60->"${m}m";m<1440->"${m/60}h";else->"${m/1440}d"}}
