package com.fynx.app.ui

import android.content.Context
import android.net.Uri
import org.json.JSONArray
import org.json.JSONObject
import java.net.URLEncoder

object FynxProfileRemoteClient {
    data class Profile(val id:String,val username:String,val displayName:String,val bio:String,val country:String,val verified:Boolean,val profilePhotoMediaId:String?,val activityVisible:Boolean,val relationship:String,val viewerSentRequest:Boolean,val viewerReceivedRequest:Boolean,val followedByCurrentUser:Boolean,val mutualFriends:Int,val postCount:Int,val followerCount:Int?=null,val followingCount:Int?=null,val connectionsVisible:Boolean=false)
    data class ProfilePost(val id:String,val text:String,val visibility:String,val mediaId:String?,val mediaType:String?,val mediaUrl:String?,val timestamp:Long,val likeCount:Int,val commentCount:Int)
    data class ConnectionUser(val id:String,val username:String,val displayName:String)
    data class Report(val id:String,val status:String)
    suspend fun get(context:Context,username:String):Result<Profile>{val encoded=URLEncoder.encode(username.trim().removePrefix("@"),"UTF-8");return FynxBackendClient.get(context,"/api/social/profile/$encoded").mapCatching{val p=JSONObject(it).getJSONObject("profile");Profile(p.optString("id"),p.optString("username"),p.optString("displayName"),p.optString("bio"),p.optString("country"),p.optBoolean("verified"),p.optString("profilePhotoMediaId").takeIf{v->v.isNotBlank()&&v!="null"},p.optBoolean("activityVisible"),p.optString("relationship"),p.optBoolean("viewerSentRequest"),p.optBoolean("viewerReceivedRequest"),p.optBoolean("followedByCurrentUser"),p.optInt("mutualFriends"),p.optInt("postCount"),if(p.has("followerCount")&&!p.isNull("followerCount"))p.optInt("followerCount") else null,if(p.has("followingCount")&&!p.isNull("followingCount"))p.optInt("followingCount") else null,p.optBoolean("connectionsVisible"))}}
    suspend fun followers(context:Context):Result<List<ConnectionUser>> = FynxBackendClient.get(context,"/api/social/me/followers").mapCatching { parseConnections(it) }
    suspend fun following(context:Context):Result<List<ConnectionUser>> = FynxBackendClient.get(context,"/api/social/me/following").mapCatching { parseConnections(it) }
    private fun parseConnections(raw:String):List<ConnectionUser>{val array=JSONObject(raw).optJSONArray("users")?:JSONArray();return buildList{for(i in 0 until array.length()){val u=array.getJSONObject(i);add(ConnectionUser(u.optString("id"),u.optString("username"),u.optString("displayName")))}}}

    suspend fun posts(context:Context,username:String):Result<List<ProfilePost>>{val encoded=URLEncoder.encode(username.trim().removePrefix("@"),"UTF-8");return FynxBackendClient.get(context,"/api/social/profile/$encoded/posts?limit=30").mapCatching{val a=JSONObject(it).optJSONArray("posts")?:JSONArray();buildList{for(i in 0 until a.length()){val p=a.getJSONObject(i);add(ProfilePost(p.optString("id"),p.optString("text"),p.optString("visibility"),p.optString("mediaId").takeIf{v->v.isNotBlank()&&v!="null"},p.optString("mediaType").takeIf{v->v.isNotBlank()&&v!="null"},p.optString("mediaUrl").takeIf{v->v.isNotBlank()},p.optDouble("timestamp").toLong(),p.optInt("likeCount"),p.optInt("commentCount")))}}}}
    suspend fun update(context:Context,displayName:String,username:String,bio:String,country:String="",profilePhotoMediaId:String?=null,removeProfilePhoto:Boolean=false):Result<Profile>{return FynxBackendClient.patchJson(context,"/api/social/profile/me",JSONObject().apply{put("displayName",displayName.trim());put("username",username.trim().removePrefix("@"));put("bio",bio.trim());put("country",country.trim());if(removeProfilePhoto)put("profilePhotoMediaId",JSONObject.NULL) else if(profilePhotoMediaId!=null)put("profilePhotoMediaId",profilePhotoMediaId.toLongOrNull()?:JSONObject.NULL)}.toString()).mapCatching{val p=JSONObject(it).getJSONObject("profile");Profile(p.optString("id"),p.optString("username"),p.optString("display_name"),p.optString("bio"),p.optString("country"),p.optBoolean("verified"),p.optString("profile_photo_media_id").takeIf{v->v.isNotBlank()&&v!="null"},true,"self",false,false,false,0,0)}}
    suspend fun uploadProfilePhoto(context:Context,uri:Uri):Result<String>{val mime=context.contentResolver.getType(uri)?.lowercase()?.takeIf{it.startsWith("image/")}?:"image/jpeg";return FynxProductionMessaging.uploadMedia(context,uri,mime).map{it.id}}
    suspend fun report(context:Context,username:String,reason:String,details:String=""):Result<Report>{val encoded=URLEncoder.encode(username.trim().removePrefix("@"),"UTF-8");return FynxBackendClient.postJson(context,"/api/social/profile/$encoded/report",JSONObject().apply{put("reason",reason.trim().ifBlank{"Other"});put("details",details.trim())}.toString()).mapCatching{val r=JSONObject(it).getJSONObject("report");Report(r.optString("id"),r.optString("status"))}}
}
